services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true

  Amzs\CoreBundle\:
    resource: '../../../src/'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../Kernel.php'
      - '../../Constant/'
      - '../../Traits/'
      - '../../AmzsCoreBundle.php'
